name: Erhöhe Versionsnummer unter Windows

on: 
  #push:  # Wird bei jedem Push ausgelöst
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'
permissions: 
  contents: write  # GitHub Actions darf ins Repo schreiben
jobs:
  test:
    runs-on: self-hosted #windows-latest
    steps:
      - name: test
        run: write-host 'Hallo'
  bump-version:
    runs-on: self-hosted #windows-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Stellt sicher, dass der vollständige Git-Verlauf verfügbar ist

      - name: Version erhöhen
        shell: pwsh  # PowerShell als Shell nutzen
        run: |
          # Datei einlesen
          $old_version = Get-Content version.txt

          # Versionsnummer erhöhen (letzte Stelle)
          $parts = $old_version -split '\.'
          $parts[-1] = [int]$parts[-1] + 1
          $new_version = $parts -join "."

          Write-Output "Erhöhe Version: $old_version -> $new_version"

          # Neue Version zurück in die Datei schreiben
          Set-Content -Path version.txt -Value $new_version
          set-content -Path test.txt -Value (whoami /groups)

          set-content -Path 'C:\Users\Marcel\AppData\Local\Temp\test123.txt' -Value 'Hallo Welt'

      - name: Änderungen committen und pushen
      
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add version.txt
          git add test.txt
          git commit -m "🔼 Version erhöht: $(Get-Content version.txt)"
          git push
